# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

#       - name: ls -a via ssh
#         uses: garygrossgarten/github-action-ssh@release
#         with:
#           command: ls -a
#           host: ${{ secrets.HOST }}
#           username: root
#           port: 22
#           privateKey: ${{ secrets.PRIVATE_KEY}}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' #Set up the Java environment to version 17
          distribution: 'adopt'

      - name: Build Platform
        run: mvn --batch-mode -DskipTests package #building the application, but skipping the tests

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test #defer the response to failed tests to the test processing action

      # Runs a single command using the runners shell
#       - name: Packing platform
#         run: |
#           cd target
#           ls
        
      - name: transit jar file to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
#           ARGS: "-rltgoDzvO"
          SOURCE: "target/project1-0.0.1-SNAPSHOT.jar"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /root/project-1/dockerfiles/platform/project1.jar  #注意这里
#           EXCLUDE: "/dist/, /node_modules/"

      - name: deploy platform
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /root/project-1/dockerfiles/platform
            docker build -t project1:1.0.1 .
            kubectl delete pod $(kubectl get pod -n project1 | grep platform | awk '{print $1}') -n project1
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          privateKey: ${{ secrets.PRIVATE_KEY}}


      # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
